// Initial subjects data
export const initialSubjects = [
  {
    id: "1",
    name: "Introduction to Programming",
    code: "CS101",
    type: "both",
    units: 3,
    lecture_units: 2,
    laboratory_units: 1,
    semester: "1st",
    year_level: "1st",
    department: "College of Information Technology",
    description: "Basic programming concepts and problem-solving techniques",
    instructors: ["John Doe", "Jane Smith"],
  },
  {
    id: "2",
    name: "Data Structures and Algorithms",
    code: "CS201",
    type: "both",
    units: 4,
    lecture_units: 3,
    laboratory_units: 1,
    semester: "2nd",
    year_level: "2nd",
    department: "College of Information Technology",
    description: "Study of fundamental data structures and algorithms",
    instructors: ["Alice Johnson", "Bob Wilson"],
  },
  {
    id: "3",
    name: "Database Management Systems",
    code: "CS301",
    type: "both",
    units: 3,
    lecture_units: 2,
    laboratory_units: 1,
    semester: "1st",
    year_level: "3rd",
    department: "College of Information Technology",
    description: "Introduction to database design and management",
    instructors: ["Charlie Brown", "Diana Miller"],
  },
  {
    id: "4",
    name: "Web Development",
    code: "CS401",
    type: "both",
    units: 3,
    lecture_units: 2,
    laboratory_units: 1,
    semester: "2nd",
    year_level: "4th",
    department: "College of Information Technology",
    description: "Modern web development technologies and practices",
    instructors: ["Eve Davis", "Frank Wilson"],
  },
  {
    id: "5",
    name: "Software Engineering",
    code: "CS501",
    type: "lecture",
    units: 3,
    lecture_units: 3,
    laboratory_units: 0,
    semester: "1st",
    year_level: "3rd",
    department: "College of Information Technology",
    description: "Software development methodologies and practices",
    instructors: ["Grace Lee", "Henry Chen"],
  },
]; 